### PR TITLE
fix(repl): Print out Char as the "character" in thre repl

### LINKED ISSUE #395: Print out Char as the "character" instead of code point integer in the repl
```f#
> 'a'
97

// Should be

> 'a'
'a'
```

### PR DESCRIPTION
**Pull request by oooooba**
Fixes #395

### CODE REVIEW

File: vm/src/value.rs [hunk 1]
```diff
@@ -439,7 +439,23 @@ impl<'a, 't> InternalPrinter<'a, 't> {
...
+            Value::Int(i) => {
+                use base::types::BuiltinType;
+                match **self.typ {
+                    Type::Builtin(BuiltinType::Int) => arena.text(format!("{}", i)),
+                    Type::Builtin(BuiltinType::Char) =>
+                        if i < ::std::u32::MAX as isize {
+                            match ::std::char::from_u32(i as u32) {
+                                Some('"') => arena.text(format!("'{}'", '"')),
+                                Some(c) => arena.text(format!("'{}'", c.escape_default())),
+                                None => unreachable!(),
```
Comment (brendanzab) [inline vm/src/value.rs]: Why the special case for `"`?

Also kind of concerning that we are storing unicode chars as `isize`s. What if they are larger than 32 bits? Not really an issue for this PR though 🤔

File: vm/src/value.rs [hunk 2]
```diff
@@ -439,7 +439,23 @@ impl<'a, 't> InternalPrinter<'a, 't> {
...
+                        if 0 <= i && i <= ::std::u32::MAX as isize {
+                            match ::std::char::from_u32(i as u32) {
+                                Some('"') => arena.text(format!("'{}'", '"')),
+                                Some(c) => arena.text(format!("'{}'", c.escape_default())),
+                                None => unreachable!(),
+                            }
+                        } else {
+                            unreachable!()
+                        },
+                    _ => unreachable!(),
```
Comment (Marwes) [inline vm/src/value.rs]: Rather than using `unreachable!` it would be better to just print out the integer as-is. That should be a sensible default regardless of what the type actually is and reduces the number of potential panics.

File: vm/src/value.rs [hunk 3]
```diff
@@ -439,7 +439,23 @@ impl<'a, 't> InternalPrinter<'a, 't> {
             Value::Userdata(ref data) => arena.text(format!("{:?}", data)),
             Value::Thread(thread) => arena.text(format!("{:?}", thread)),
             Value::Byte(b) => arena.text(format!("{}", b)),
-            Value::Int(i) => arena.text(format!("{}", i)),
+            Value::Int(i) => {
+                use base::types::BuiltinType;
+                match **self.typ {
+                    Type::Builtin(BuiltinType::Int) => arena.text(format!("{}", i)),
+                    Type::Builtin(BuiltinType::Char) =>
+                        if 0 <= i && i <= ::std::u32::MAX as isize {
```
Comment (Marwes) [inline vm/src/value.rs]: I think it should be fine to just omit this comparison. When `isize` is 32-bit I think `i as u32` should should preserve all the bits (that is, `i as i32 as u32 == i`).

File: vm/src/value.rs [hunk 4]
```diff
@@ -439,7 +439,23 @@ impl<'a, 't> InternalPrinter<'a, 't> {
...
+                            match ::std::char::from_u32(i as u32) {
+                                Some('"') => arena.text(format!("'{}'", '"')),
+                                Some(c) => arena.text(format!("'{}'", c.escape_default())),
+                                None => unreachable!(),
```
Comment (Marwes) [inline vm/src/value.rs]: Could you change this to  something akin to `ìce!("Invalid character passed to pretty printing")` (`ice!` reports in internal compiler error with a link to gluon's issue list).

(Using `unreachable!` is fine but I think it is best to limit it to places where it is possible to locally verify that the branch is `unreachable`. Here the character can be created far away from this branch)

**Comment by Marwes** [comment]
@brendanzab
> Also kind of concerning that we are storing unicode chars as isizes. What if they are larger than 32 bits? Not really an issue for this PR though 🤔

I'd view `Value`'s variants more like different "representations" of data instead of them having knowledge about the underlying type. Though it would be easy to add `Value::Char` I have avoided that since 1, I am lazy, 2, if we implement nan-boxing (#303) of values then we will be limited to 8 (I think) variants in which case we can't "waste" variants on primitive non-boxed types such as `Char`.

**Comment by brendanzab** [comment]
More the issue is that it makes characters system-dependant, and reduces the number of valid unicode characters we can store.

File: vm/src/value.rs (hunk 4 above)
Comment (brendanzab) [reply vm/src/value.rs]: Is it really an internal compiler error though? This is more of a runtime problem, no?

Comment (Marwes) [reply vm/src/value.rs]: Well the "compiler" (speaking about it in a broader sense) has made a mistake causing an invalid character to be stored. Is there any reason to separate "Internal compiler errors" from "Internal virtual machine errors"?

**Comment by Marwes** [comment]
> More the issue is that it makes characters system-dependant, and reduces the number of valid unicode characters we can store.

Only if isize is 16-bit though, since the integer will just be treated as a set of 32 bits rather than a signed integer. I opened https://github.com/gluon-lang/gluon/issues/403 though since `VmInt` should be fixed size.

File: vm/src/value.rs (hunk 3 above)
Comment (oooooba) [reply vm/src/value.rs]: When `isize` is 64-bit, how can I deal with it?
Should I forcibly cast i to u32, then call `char::from_u32` (that is, `char::from_u32(i as u32)`)?

Comment (Marwes) [reply vm/src/value.rs]: Yep. Just truncating with `as` is fine.

File: vm/src/value.rs (hunk 1 above)
Comment (oooooba) [reply vm/src/value.rs]: `char::escape_default` returns `'\"'` for input `'"'`.
https://doc.rust-lang.org/std/primitive.char.html#method.escape_default
I thought that input `'"'` to repl should corresponds to output `'"',` and treated it specially.

**Comment by Marwes** [comment]
👍 Thanks!
